export const lifeList = [
        {
            id: "ibis-001",
            commonName: "White Ibis",
            scientificName: "Eudocimus albus",
            sightingsThisYear: 4,
            totalSightings: 10,
            bird: {
                id: "ibis-001",
                image: "/ibis.jpg",
                commonName: "White Ibis",
                scientificName: "Eudocimus albus",
            },
            media: []
        },
        {
            id: "great-blue-heron-001",
            commonName: "Great Blue Heron",
            scientificName: "Ardea herodias",
            sightingsThisYear: 8,
            totalSightings: 24,
        },
        {
            id: "snowy-egret-001",
            commonName: "Snowy Egret",
            scientificName: "Egretta thula",
            sightingsThisYear: 6,
            totalSightings: 18,
        },
        {
            id: "wood-duck-001",
            commonName: "Wood Duck",
            scientificName: "Aix sponsa",
            sightingsThisYear: 3,
            totalSightings: 7,
        },
        {
            id: "mallard-001",
            commonName: "Mallard",
            scientificName: "Anas platyrhynchos",
            sightingsThisYear: 5,
            totalSightings: 15,
        },
        {
            id: "red-tailed-hawk-001",
            commonName: "Red-tailed Hawk",
            scientificName: "Buteo jamaicensis",
            sightingsThisYear: 7,
            totalSightings: 22,
        },
        {
            id: "bald-eagle-001",
            commonName: "Bald Eagle",
            scientificName: "Haliaeetus leucocephalus",
            sightingsThisYear: 2,
            totalSightings: 8,
        },
        {
            id: "osprey-001",
            commonName: "Osprey",
            scientificName: "Pandion haliaetus",
            sightingsThisYear: 4,
            totalSightings: 12,
        },
        {
            id: "clapper-rail-001",
            commonName: "Clapper Rail",
            scientificName: "Rallus crepitans",
            sightingsThisYear: 2,
            totalSightings: 6,
        },
        {
            id: "killdeer-001",
            commonName: "Killdeer",
            scientificName: "Charadrius vociferus",
            sightingsThisYear: 6,
            totalSightings: 16,
        },
        {
            id: "willet-001",
            commonName: "Willet",
            scientificName: "Catoptrophorus semipalmatus",
            sightingsThisYear: 5,
            totalSightings: 13,
        },
        {
            id: "laughing-gull-001",
            commonName: "Laughing Gull",
            scientificName: "Leucophaeus atricilla",
            sightingsThisYear: 9,
            totalSightings: 28,
        },
        {
            id: "herring-gull-001",
            commonName: "Herring Gull",
            scientificName: "Larus argentatus",
            sightingsThisYear: 7,
            totalSightings: 20,
        },
        {
            id: "forsters-tern-001",
            commonName: "Forster's Tern",
            scientificName: "Sterna forsteri",
            sightingsThisYear: 4,
            totalSightings: 11,
        },
        {
            id: "american-crow-001",
            commonName: "American Crow",
            scientificName: "Corvus brachyrhynchos",
            sightingsThisYear: 11,
            totalSightings: 35,
        },
        {
            id: "fish-crow-001",
            commonName: "Fish Crow",
            scientificName: "Corvus ossifragus",
            sightingsThisYear: 8,
            totalSightings: 25,
        },
        {
            id: "carolina-wren-001",
            commonName: "Carolina Wren",
            scientificName: "Thryothorus ludovicianus",
            sightingsThisYear: 6,
            totalSightings: 18,
        },
        {
            id: "northern-mockingbird-001",
            commonName: "Northern Mockingbird",
            scientificName: "Mimus polyglottos",
            sightingsThisYear: 7,
            totalSightings: 21,
        },
        {
            id: "american-robin-001",
            commonName: "American Robin",
            scientificName: "Turdus migratorius",
            sightingsThisYear: 5,
            totalSightings: 14,
        },
        {
            id: "eastern-bluebird-001",
            commonName: "Eastern Bluebird",
            scientificName: "Sialia sialis",
            sightingsThisYear: 3,
            totalSightings: 9,
        },
        {
            id: "pine-warbler-001",
            commonName: "Pine Warbler",
            scientificName: "Setophaga pinus",
            sightingsThisYear: 4,
            totalSightings: 10,
        },
        {
            id: "yellow-rumped-warbler-001",
            commonName: "Yellow-rumped Warbler",
            scientificName: "Setophaga coronata",
            sightingsThisYear: 8,
            totalSightings: 23,
        },
        {
            id: "northern-cardinal-001",
            commonName: "Northern Cardinal",
            scientificName: "Cardinalis cardinalis",
            sightingsThisYear: 9,
            totalSightings: 30,
        },
        {
            id: "house-finch-001",
            commonName: "House Finch",
            scientificName: "Haemorhous mexicanus",
            sightingsThisYear: 5,
            totalSightings: 16,
        },
        {
            id: "american-goldfinch-001",
            commonName: "American Goldfinch",
            scientificName: "Spinus tristis",
            sightingsThisYear: 6,
            totalSightings: 18,
        },
]